package MayoBot;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import MayoBot.commands.DeadlineCommand;
import MayoBot.commands.DeleteCommand;
import MayoBot.commands.EventCommand;
import MayoBot.commands.FindCommand;
import MayoBot.commands.MarkCommand;
import MayoBot.commands.TodoCommand;
import MayoBot.commands.UnknownCommand;
import MayoBot.commands.UnmarkCommand;
import MayoBot.exceptions.UnknownCommandException;
import MayoBot.task.DeadlineTask;
import MayoBot.task.EventTask;
import MayoBot.task.Task;
import MayoBot.task.TodoTask;
import MayoBot.commands.ByeCommand;
import MayoBot.commands.Command;
import MayoBot.commands.ListCommand;

/**
 * Utility class for parsing user input and file data into Command and Task objects.
 * Provides static methods to convert string inputs into structured data that the application can process.
 * <p>
 * This class handles two main types of parsing:
 * - User command input parsing for interactive commands
 * - File data parsing for task persistence and loading
 */
public class Parser {
    /** Date and time formatter for parsing date strings in DD-MM-YYYY HH:mm format. */
    private static final DateTimeFormatter INPUT_FORMAT = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");

    /**
     * Returns a Command object by parsing user input string containing the command type and arguments.
     * Splits the input on the first space to separate the command word from its arguments.
     * The first word becomes the command, and everything after the first space becomes the arguments.
     *
     * @param input the raw user input string to be parsed
     * @return a Command object containing the parsed command word and arguments string
     * @see Command
     */
    public static Command parse(String input) {
        String[] parts = input.split(" ", 2);
        String command = parts[0];
        String arguments = parts.length > 1 ? parts[1] : "";
        return constructCommand(command, arguments);
    }

    /**
     * Returns a Task object by parsing a task string from file storage format.
     * Supports parsing TodoTask, DeadlineTask, and EventTask from their stored format.
     * The expected format is: "TYPE | DONE_STATUS | DESCRIPTION [| DATETIME_FIELDS]"
     * where TYPE is T/D/E, DONE_STATUS is 0/1, and DATETIME_FIELDS vary by task type.
     * <p>
     * This method returns null if the input format is invalid or cannot be parsed.
     * Datetime parsing follows ISO format as generated by LocalDateTime.toString().
     *
     * @param input the task string in file storage format
     * @return the parsed Task object, or null if the input format is invalid
     * @see TodoTask
     * @see DeadlineTask
     * @see EventTask
     */
    public static Task parseTaskFromFile(String input) {
        String[] parts = input.split(" \\| ");
        if (parts.length < 3) {
            return null;
        }

        String type = parts[0];
        boolean isDone = parts[1].equals("1");
        String description = parts[2];

        Task task = null;
        switch (type) {
        case "T":
            task = new TodoTask(description);
            break;
        case "D":
            if (parts.length >= 4) {
                LocalDateTime by = LocalDateTime.parse(parts[3]);
                task = new DeadlineTask(description, by);
            }
            break;
        case "E":
            if (parts.length >= 5) {
                LocalDateTime from = LocalDateTime.parse(parts[3]);
                LocalDateTime to = LocalDateTime.parse(parts[4]);
                task = new EventTask(description, from, to);
            }
            break;
        default:
            return null;
        }

        if (task != null && isDone) {
            task.markAsDone();
        }
        return task;
    }

    private static Command constructCommand(String command, String arguments) {
        switch (command) {
        case "list":
            return new ListCommand(arguments);
        case "bye":
            return new ByeCommand(arguments);
        case "mark":
            return new MarkCommand(arguments);
        case "unmark":
            return new UnmarkCommand(arguments);
        case "delete":
            return new DeleteCommand(arguments);
        case "find":
            return new FindCommand(arguments);
        case "todo":
            return new TodoCommand(arguments);
        case "deadline":
            return new DeadlineCommand(arguments);
        case "event":
            return new EventCommand(arguments);
        default:
            return new UnknownCommand(command, arguments);
        }
    }
}
